**Подготовка файла 2800.csv на основе данных сводных файлов 2016-2018 годов**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

- `..\Data\{год}\` - папка для хранения созданнного 2200.csv для определенного года
- `..\Data\{год}\Original` - папка для хранения оригинального файла xlsx
- `..\Data\Common\` - папка для хранения итогового результата 2200.csv сводный

Пример: 
- *E:/IrkutskProject/Data/2016/Original/ф33  правл за 2016г Иркутская обл.xlsx*
- *E:/IrkutskProject/Data/2016/2200.csv*

In [4]:
# Загрузка библиотек
import pandas as pd
import numpy as np

In [5]:
# Установка библиотеки для чтения excel. 
# !pip install openpyxl
# !pip install xlrd

In [6]:
# Проверка версии
# pip show openpyxl

1) Подкотовка датасетов формы 2800 за 2016-2018 года

In [8]:
# Список годов для обработки
#years = [2016, 2017, 2018]

# Название оригинального файла
#original_names = {
#    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
#    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
#    2018: 'ф.33 и ф.8  Иркутская область  2018.xls'
#}

years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

# Название оригинального файла
original_names = {
    2016: 'ф33  правл за 2016г Иркутская обл.xlsx',
    2017: 'ф.33 и ф.8 Иркутская область 2017г..xls',
    2018: 'ф.33 и ф.8  Иркутская область  2018.xls',
    2019: 'Свод ф.33 ,ф.8 область правильный 03.02. 2019.xls',
    2020: 'Свод ф.33,8  Иркутская область 2020 верный.xls',
    2021: 'свод область 2021  верный .xls',
    2022: 'свод верн Иркутская область 2022г  ф.33, 8.xls',
    2023: 'свод  Иркутская область верн 2023г..xls',
    2024: 'свод область 2024г.ф.33,8 верн Иркутская обл.xls'
}
original_url = {}
path = 'E:/IrkutskProject/Data/'

df_2800 = {}

for year in years:
    original_path = f'{path}{year}/Original/'
    original_url[year] = original_path + original_names[year]
    
    if year == 2016:
        df = pd.read_excel(original_url[year], engine='openpyxl', sheet_name = '2700-2710')

        # Отфильтруем таблицу 2800
        df_2800[year] = df.iloc[27:36]
    else:
        df = pd.read_excel(original_url[year], engine='xlrd', sheet_name='2600-2800')
            
        # Отфильтруем таблицу 2800
        df_2800[year] = df.iloc[23:33]

        df_2800[year] = df_2800[year].drop(df_2800[year].columns[13:14], axis=1)
        df_2800[year] = df_2800[year].drop(df_2800[year].columns[0:10], axis=1)
        df_2800[year] = df_2800[year].dropna(how='all')
        

    df_2800[year] = df_2800[year].dropna(how='all', axis=1)
    #df_2800[year] = df_2800[year].drop(df_2800[year].columns[1:2], axis=1)
    #df_2800[year].drop(df_2800[year].index[1:2], inplace=True)
       
    # Переименовываем колонки
    #df_2800[year].columns = ['Наименование показателей', 'Всего', 'Из них детей от 0 до 14 лет', 'Из них подростков от 15 до 17 лет']
    df_2800[year].columns = [0, 1, 2, 3, 4]
    df_2800[year] = df_2800[year].reset_index(drop=True)
    
    # Подписываем строки в соответствии с шаблоном
    df_2800[year].iloc[2, 0] = 'Выявлено в текущем году'
    df_2800[year].iloc[3, 0] = 'Выявлено в текущем году, из  них с МБТ+'
    df_2800[year].iloc[4, 0] = 'Наблюдалось в отчетном году'
    df_2800[year].iloc[5, 0] = 'Лечились в стационаре'
    df_2800[year].iloc[6, 0] = 'Лечились амбулаторно'
    df_2800[year].iloc[7, 0] = 'Умерло от туберкулеза всего'
    df_2800[year].iloc[8, 0] = 'Умерло от туберкулеза всего, из них в стационаре'

    df_2800[year].iloc[0, 2] = 'Всего'
    df_2800[year].iloc[0, 3] = 'Из них детей от 0 до 14 лет'
    df_2800[year].iloc[0, 4] = 'Из них подростков от 15 до 17 лет'

    for j in range(1, 6):
        df_2800[year].iloc[1, j - 1] = f'{j}'

    for i in range(1, 8):
        df_2800[year].iloc[i + 1, 1] = f'{i}'

    df_2800[year].to_csv(f'E:/IrkutskProject/Data/{year}/2800.csv', index=False)

In [9]:
df_2800[2016]

,0,1,2,3,4
0,NaN,NaN,Всего,Из них детей от 0 до 14 лет,Из них подростков от 15 до 17 лет
1,1,2,3,4,5
2,Выявлено в текущем году,1,16,NaN,NaN
3,"Выявлено в текущем году, из них с МБТ+",2,1,NaN,NaN
4,Наблюдалось в отчетном году,3,5,NaN,NaN
5,Лечились в стационаре,4,1,NaN,NaN
6,Лечились амбулаторно,5,4,NaN,NaN
7,Умерло от туберкулеза всего,6,NaN,NaN,NaN
8,"Умерло от туберкулеза всего, из них в стационаре",7,NaN,NaN,NaN

In [10]:
columns = [
    'Показатель',
    'Возраст',
    'Год',
    'Значение',
    'Строка',
    'Графа',
    'Таблица'
]

data = []
data_2016_2018 = []

df_2800_long = pd.DataFrame(columns=columns)
df_2800_long_2016_2018 = pd.DataFrame(columns=columns)

for year in years:
    for row_number in range(2, df_2800[year].shape[0]):
        for col_number in range(2, 5):
            new_row = []
            new_row.append(df_2800[year].iloc[row_number, 0].strip())
            new_row.append(df_2800[year].iloc[0, col_number])
            new_row.append(year)
            #new_row.append(df_2800[year].iloc[row_number, col_number] if pd.notnull(df_2800[year].iloc[row_number, col_number]) else 0)
            
            new_row.append(df_2800[year].iloc[row_number, col_number] if (
                (df_2800[year].iloc[row_number, col_number] != 'X') and # английская X
                (df_2800[year].iloc[row_number, col_number] != 'Х')) # русская Х
            else np.nan)
            
            new_row.append(df_2800[year].iloc[row_number, 1])
            new_row.append(df_2800[year].iloc[1, col_number])
            new_row.append(2800)
            data.append(new_row)
            if year <= 2018:
                data_2016_2018.append(new_row)
            
df_2800_long = pd.DataFrame(data, columns=columns)
df_2800_long_2016_2018 = pd.DataFrame(data_2016_2018, columns=columns)

df_2800_long

,Показатель,Возраст,Год,Значение,Строка,Графа,Таблица
0,Выявлено в текущем году,Всего,2016,16.0,1,3,2800
1,Выявлено в текущем году,Из них детей от 0 до 14 лет,2016,NaN,1,4,2800
2,Выявлено в текущем году,Из них подростков от 15 до 17 лет,2016,NaN,1,5,2800
3,"Выявлено в текущем году, из них с МБТ+",Всего,2016,1.0,2,3,2800
4,"Выявлено в текущем году, из них с МБТ+",Из них детей от 0 до 14 лет,2016,NaN,2,4,2800
...,...,...,...,...,...,...,...
184,Умерло от туберкулеза всего,Из них детей от 0 до 14 лет,2024,0.0,6,4,2800
185,Умерло от туберкулеза всего,Из них подростков от 15 до 17 лет,2024,0.0,6,5,2800
186,"Умерло от туберкулеза всего, из них в стационаре",Всего,2024,0.0,7,3,2800
187,"Умерло от туберкулеза всего, из них в стационаре",Из них детей от 0 до 14 лет,2024,0.0,7,4,2800
188,"Умерло от туберкулеза всего, из них в стационаре",Из них подростков от 15 до 17 лет,2024,0.0,7,5,2800

In [11]:
df_2800_long_2016_2018.to_csv(f'{path}Common_2016-2018/2800_2016-2018.csv', index=False)
df_2800_long.to_csv(f'{path}Common/2800_2016-2024.csv', index=False)