**Dataset Социально-Значемые заболенвания и гео-точки**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('E:/IrkutskProject/Data/Common/tuberculosis_dashboard_2016-2024.csv')
df_clarified = pd.read_csv('E:/IrkutskProject/Data/Common/tuberculosis_dashboard_clarified_2016-2024.csv')
#df_geo = pd.read_csv('E:/IrkutskProject/DataLens/ru_regions.csv', sep=';')
df_geo = pd.read_csv('E:/IrkutskProject/DataLens/polygons.csv')

In [4]:
df.shape

(765, 8)

In [5]:
df_geo.shape

(85, 2)

In [6]:
display(df.head())
display(df_geo.head())

,Округ,Субъект,Год,Число пациентов с впервые в жизни установ.диагнозом. Абс.знач.,Число пациентов с впервые в жизни установ.диагнозом. На 100.тыс.,Число пациентов состоящих под диспансерным наблюдением на конец года. Абс.знач.,Число пациентов состоящих под диспансерным наблюдением на конец года. На 100.тыс.,Источник
0,Центральный федеральный округ,Белгородская область,2016,333,21.5,428,27.6,soc_znach2016.docx
1,Центральный федеральный округ,Брянская область,2016,655,53.4,1389,113.3,soc_znach2016.docx
2,Центральный федеральный округ,Владимирская область,2016,510,36.5,855,61.2,soc_znach2016.docx
3,Центральный федеральный округ,Воронежская область,2016,665,28.5,1378,59.1,soc_znach2016.docx
4,Центральный федеральный округ,Ивановская область,2016,439,42.6,642,62.3,soc_znach2016.docx

                  region                                            polygon
0  Архангельская область  [[[65.051193, 35.314801], [65.127703, 35.29793...
1         Алтайский край  [[[53.290641, 77.907506], [53.367469, 77.88941...
2       Амурская область  [[[56.865828, 119.818979], [56.903958, 119.884...
3   Астраханская область  [[[48.270856, 44.962711], [48.291774, 44.98271...
4   Белгородская область  [[[50.97531, 35.352225], [50.958115, 35.411367...

In [7]:
# Обработка данных для геоточек
#df_points = df
#df_points_clarified = df_clarified
#df_points['region'] = (df_points['Субъект'])
#df_points_clarified['region'] = (df_points_clarified['Субъект'])

#df_points['region'] = (df_points['Субъект']
#                .replace('город Москва','Москва')
#                .replace('город Санкт - Петербург','Санкт-Петербург')
#                .replace('город Севастополь','Севастополь')
#                .replace('Кабардино-Балкарская Республика','Республика Кабардино-Балкария')
#                .replace('Карачаево-Черкесская Республика','Республика Карачаево-Черкесия')
#                .replace('Чеченская Республика','Республика Чечня')
#                .replace('Удмуртская Республика','Республика Удмуртия')
#                .replace('Чувашская Республика','Республика Чувашия')
#                .replace('Архангельская область без автономного округа','Архангельская область')
#                .replace('Тюменская область без автономного округа','Тюменская область')
#                .replace('Ханты-Мансийский АО','Ханты-Мансийский (Югра) автономный округ')
#                .replace('Ямало-Hенецкий АО','Ямало-Ненецкий автономный округ')
#               )
                
#df_points_clarified['region'] = (df_points_clarified['Субъект']
#                .replace('город Москва','Москва')
#                .replace('город Санкт - Петербург','Санкт-Петербург')
#                .replace('город Севастополь','Севастополь')
#                .replace('Кабардино-Балкарская Республика','Республика Кабардино-Балкария')
#                .replace('Карачаево-Черкесская Республика','Республика Карачаево-Черкесия')
#                .replace('Чеченская Республика','Республика Чечня')
#                .replace('Удмуртская Республика','Республика Удмуртия')
#                .replace('Чувашская Республика','Республика Чувашия')
#                .replace('Архангельская область без автономного округа','Архангельская область')
#                .replace('Тюменская область без автономного округа','Тюменская область')
#                .replace('Ханты-Мансийский АО','Ханты-Мансийский (Югра) автономный округ')
#                .replace('Ямало-Hенецкий АО','Ямало-Ненецкий автономный округ')
#               )
#df_points

In [8]:
#df_with_geo_points = pd.merge(df_points, df_geo[df_geo['coords_type'] == 'ru_regions_points'][['region','coords_type','coords']], how = 'left', on = 'region')
#df_with_geo_points_clarified = pd.merge(df_points_clarified, df_geo[df_geo['coords_type'] == 'ru_regions_points'][['region','coords_type','coords']], how = 'left', on = 'region')

#display(df_with_geo_points.shape)
#display(df_with_geo_points)

In [9]:
# Обрабока данных для полигонов
df_polly = df
df_polly_clarified = df_clarified

df_polly['region'] = (df_polly['Субъект']
                .replace('город Москва','Москва')
                .replace('город Санкт - Петербург','Санкт-Петербург')
                .replace('город Севастополь','Севастополь')
                #.replace('Кабардино-Балкарская Республика','Республика Кабардино-Балкария')
                #.replace('Карачаево-Черкесская Республика','Республика Карачаево-Черкесия')
                #.replace('Чеченская Республика','Республика Чечня')
                #.replace('Удмуртская Республика','Республика Удмуртия')
                #.replace('Чувашская Республика','Республика Чувашия')
                .replace('Республика Северная Осетия - Алания', 'Республика Северная Осетия — Алания')
                .replace('Чувашская Республика','Чувашская Республика — Чувашия')
                .replace('Архангельская область без автономного округа','Архангельская область')
                .replace('Тюменская область без автономного округа','Тюменская область')
                .replace('Ханты-Мансийский АО','Ханты-Мансийский автономный округ — Югра')
                .replace('Ямало-Hенецкий АО','Ямало-Ненецкий автономный округ')
               )
df_polly_clarified['region'] = (df_polly_clarified['Субъект']
                .replace('город Москва','Москва')
                .replace('город Санкт - Петербург','Санкт-Петербург')
                .replace('город Севастополь','Севастополь')
                #.replace('Кабардино-Балкарская Республика','Республика Кабардино-Балкария')
                #.replace('Карачаево-Черкесская Республика','Республика Карачаево-Черкесия')
                #.replace('Чеченская Республика','Республика Чечня')
                #.replace('Удмуртская Республика','Республика Удмуртия')
                #.replace('Чувашская Республика','Республика Чувашия')
                .replace('Республика Северная Осетия - Алания', 'Республика Северная Осетия — Алания')
                .replace('Чувашская Республика','Чувашская Республика — Чувашия')
                .replace('Архангельская область без автономного округа','Архангельская область')
                .replace('Тюменская область без автономного округа','Тюменская область')
                .replace('Ханты-Мансийский АО','Ханты-Мансийский автономный округ — Югра')
                .replace('Ямало-Hенецкий АО','Ямало-Ненецкий автономный округ')
                )

#df_polly['region'] = (df_polly['region'].apply(lambda x: x.replace('Республика', 'республика')))

In [10]:
#mask = df_polly['Субъект'].str.contains('Республика')
#df_polly[mask].head(30)
df_polly

,Округ,Субъект,Год,Число пациентов с впервые в жизни установ.диагнозом. Абс.знач.,Число пациентов с впервые в жизни установ.диагнозом. На 100.тыс.,Число пациентов состоящих под диспансерным наблюдением на конец года. Абс.знач.,Число пациентов состоящих под диспансерным наблюдением на конец года. На 100.тыс.,Источник,region
0,Центральный федеральный округ,Белгородская область,2016,333,21.5,428,27.6,soc_znach2016.docx,Белгородская область
1,Центральный федеральный округ,Брянская область,2016,655,53.4,1389,113.3,soc_znach2016.docx,Брянская область
2,Центральный федеральный округ,Владимирская область,2016,510,36.5,855,61.2,soc_znach2016.docx,Владимирская область
3,Центральный федеральный округ,Воронежская область,2016,665,28.5,1378,59.1,soc_znach2016.docx,Воронежская область
4,Центральный федеральный округ,Ивановская область,2016,439,42.6,642,62.3,soc_znach2016.docx,Ивановская область
...,...,...,...,...,...,...,...,...,...
760,Дальневосточный федеральный округ,Амурская область,2024,423,56.4,1146,152.8,11_Социально_значимые_заболевания_населения_Ро...,Амурская область
761,Дальневосточный федеральный округ,Магаданская область,2024,44,33.0,67,50.2,11_Социально_значимые_заболевания_населения_Ро...,Магаданская область
762,Дальневосточный федеральный округ,Сахалинская область,2024,235,51.4,401,87.6,11_Социально_значимые_заболевания_населения_Ро...,Сахалинская область
763,Дальневосточный федеральный округ,Еврейская автономная область,2024,127,87.1,202,138.5,11_Социально_значимые_заболевания_населения_Ро...,Еврейская автономная область
764,Дальневосточный федеральный округ,Чукотский автономный округ,2024,48,99.9,126,262.3,11_Социально_значимые_заболевания_населения_Ро...,Чукотский автономный округ

In [11]:
#df_with_geo_poly = pd.merge(df_polly, df_geo[df_geo['coords_type'] == 'ru_regions_poly'][['region','coords_type','coords']], how = 'left', on = 'region')
#df_with_geo_poly_clarified = pd.merge(df_polly_clarified, df_geo[df_geo['coords_type'] == 'ru_regions_poly'][['region','coords_type','coords']], how = 'left', on = 'region')
df_with_geo_poly = pd.merge(df_polly, df_geo, how = 'left', on = 'region')
df_with_geo_poly_clarified = pd.merge(df_polly_clarified, df_geo, how = 'left', on = 'region')

display(df_with_geo_poly.shape)
display(df_with_geo_poly)

(765, 10)

,Округ,Субъект,Год,Число пациентов с впервые в жизни установ.диагнозом. Абс.знач.,Число пациентов с впервые в жизни установ.диагнозом. На 100.тыс.,Число пациентов состоящих под диспансерным наблюдением на конец года. Абс.знач.,Число пациентов состоящих под диспансерным наблюдением на конец года. На 100.тыс.,Источник,region,polygon
0,Центральный федеральный округ,Белгородская область,2016,333,21.5,428,27.6,soc_znach2016.docx,Белгородская область,"[[[50.97531, 35.352225], [50.958115, 35.411367..."
1,Центральный федеральный округ,Брянская область,2016,655,53.4,1389,113.3,soc_znach2016.docx,Брянская область,"[[[53.911337, 34.146682], [53.908911, 34.14098..."
2,Центральный федеральный округ,Владимирская область,2016,510,36.5,855,61.2,soc_znach2016.docx,Владимирская область,"[[[56.524305, 38.268605], [56.526572, 38.27968..."
3,Центральный федеральный округ,Воронежская область,2016,665,28.5,1378,59.1,soc_znach2016.docx,Воронежская область,"[[[51.637092, 38.140099], [51.670452, 38.16122..."
4,Центральный федеральный округ,Ивановская область,2016,439,42.6,642,62.3,soc_znach2016.docx,Ивановская область,"[[[56.771178, 39.400991], [56.779082, 39.40670..."
...,...,...,...,...,...,...,...,...,...,...
760,Дальневосточный федеральный округ,Амурская область,2024,423,56.4,1146,152.8,11_Социально_значимые_заболевания_населения_Ро...,Амурская область,"[[[56.865828, 119.818979], [56.903958, 119.884..."
761,Дальневосточный федеральный округ,Магаданская область,2024,44,33.0,67,50.2,11_Социально_значимые_заболевания_населения_Ро...,Магаданская область,"[[[62.045052, 144.737377], [62.092914, 144.731..."
762,Дальневосточный федеральный округ,Сахалинская область,2024,235,51.4,401,87.6,11_Социально_значимые_заболевания_населения_Ро...,Сахалинская область,"[[[51.050461, 155.551768], [51.032687, 155.700..."
763,Дальневосточный федеральный округ,Еврейская автономная область,2024,127,87.1,202,138.5,11_Социально_значимые_заболевания_населения_Ро...,Еврейская автономная область,"[[[48.881719, 130.626261], [48.89392, 130.6281..."
764,Дальневосточный федеральный округ,Чукотский автономный округ,2024,48,99.9,126,262.3,11_Социально_значимые_заболевания_населения_Ро...,Чукотский автономный округ,"[[[67.415169, 157.900631], [67.44862, 157.7927..."

In [12]:
path = 'E:/IrkutskProject/Data/'
#df_with_geo_points.to_csv(f'{path}Common/geo_tuberculosis_points_2016-2024.csv', index=False)
#df_with_geo_points_clarified.to_csv(f'{path}Common/geo_tuberculosis_points_2016-2024_clarified.csv', index=False)
df_with_geo_poly.to_csv(f'{path}Common/geo_tuberculosis_poly_2016-2024.csv', index=False)
df_with_geo_poly_clarified.to_csv(f'{path}Common/geo_tuberculosis_poly_2016-2024_clarified.csv', index=False)