**Выгрузка численности населения с сайта Росстата Иркутской области**

- Автор: Клинкова Екатерина
- Telegram: @ekaklinkova

In [3]:
pip install requests beautifulsoup4 pandas openpyxl lxml

Requirement already satisfied: requests in c:\users\lenovo\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\lenovo\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\lenovo\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: lxml in c:\users\lenovo\anaconda3\lib\site-packages (5.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests) (2026.1.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import BytesIO
import re
import math

In [5]:
def rosstat_to_df(file_name, page_name):
    # URL страницы
    url = 'https://38.rosstat.gov.ru/folder/167937'

    try:
        # Получаем содержимое страницы
        response = requests.get(url, timeout=30, verify=False)  # без сертификата
        response.raise_for_status()
    
        # Парсим HTML
        soup = BeautifulSoup(response.content, 'html.parser')
    
        # Ищем ссылку на файл с нужным названием
        target_file = None
        for link in soup.find_all('a', href=True):

            link_text = link.get_text(strip=True)
            href = link['href']
        
            # Проверяем, содержит ли текст ссылки нужное название
            #file_name = 'Численность мужчин и женщин'
            #file_name = 'Иркутская область_2012_2021_с учетом итогов Всероссийской переписи населения 2020 года'
        
            if file_name in href:
                # Формируем полный URL
                if href.startswith('http'):
                    target_file = href
                elif href.startswith('/'):
                    # Если ссылка относительная, добавляем домен
                    base_url = 'https://38.rosstat.gov.ru'
                    target_file = base_url + href
                else:
                    # Если ссылка относительно текущей страницы
                    target_file = url.rstrip('/') + '/' + href
                break
    
        if not target_file:
            raise FileNotFoundError("Файл с указанным названием не найден на странице")
    
        print(f"Найден файл: {target_file}")
    
        # Загружаем Excel‑файл
        file_response = requests.get(target_file, timeout=30, verify=False) # без сертификата
        file_response.raise_for_status()
    
        # Создаём объект BytesIO из содержимого файла
        excel_file = BytesIO(file_response.content)
    
        # Читаем Excel в датасет
        # df = pd.read_excel(excel_file)
    
        #df_population = pd.read_excel(excel_file, engine='openpyxl', sheet_name = page_name)
        df_population = pd.read_excel(excel_file, engine='xlrd', sheet_name = page_name)
        display(year)
        display(df_population.head(10))
        
        print("Файл успешно загружен в датасет!")
    
    except requests.exceptions.RequestException as e:
        print(f"Ошибка при загрузке страницы или файла: {e}")
    except FileNotFoundError as e:
        print(e)
    except Exception as e:
        print(f"Ошибка при обработке файла: {e}")
    return df_population

In [6]:
years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

file_name = {
    2016: 'pol_voz_2016(1)_626391.xls',
    2017: 'pol_voz_2017_626392.xls',
    2018: 'pol_voz_2018_626393.xls',
    2019: 'pol_voz_2019_626395.xls',
    2020: 'Численность населения по полу и возрасту на начало 2020 года_626396.xls',
    2021: 'Численность населения по полу и возрасту на начало 2021 года_626398.xls',
    2022: 'Численность населения по полу и возрасту на 1 января 2022 года (с учетом итогов ВПН-2020).xls',
    2023: 'Численность населения по полу и возрасту на начало 2023 года(1).xls',
    2024: 'Численность населения по полу и возрасту на начало 2024 года..xls'
}

In [7]:
df_population = {}
for year in years:
    if year == 2019:
        page_name = 'Иркутская обл.'
    elif (year == 2022) or (year == 2024):
        page_name = 'Область'
    else:
        page_name = 'Иркутская область'
    df_population[year] = rosstat_to_df(file_name[year], page_name)
    df_population[year].to_csv(f'E:/IrkutskProject/Data/{year}/df_population_{year}.csv')
    #display(df_population[year])

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/pol_voz_2016(1)_626391.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2016

,Численность населения по полу и возрасту на 1 января 2016 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,человек
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2412800,1115508,1297292,1905217,867070,1038147,507583,248438,259145
7,0,2,36674,18799,17875,28359,14517,13842,8315,4282,4033
8,1,3,36392,18700,17692,26993,13871,13122,9399,4829,4570
9,2,4,37306,19185,18121,27834,14331,13503,9472,4854,4618

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/pol_voz_2017_626392.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2017

,Численность населения по полу и возрасту на 1 января 2017 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,человек
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2408901,1113729,1295172,1900330,864380,1035950,508571,249349,259222
7,0,2,35383,18407,16976,27315,14191,13124,8068,4216,3852
8,1,3,36521,18708,17813,28245,14449,13796,8276,4259,4017
9,2,4,36269,18653,17616,26910,13844,13066,9359,4809,4550

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/pol_voz_2018_626393.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2018

,Численность населения по полу и возрасту на 1 января 2018 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2404195,1111049,1293146,1894053,860701,1033352,510142,250348,259794
7,0,2,32028,16322,15706,24455,12482,11973,7573,3840,3733
8,1,3,35304,18371,16933,27249,14150,13099,8055,4221,3834
9,2,4,36440,18679,17761,28206,14450,13756,8234,4229,4005

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/pol_voz_2019_626395.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2019

,Численность населения по полу и возрасту на 1 января 2019 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2397763,1107831,1289932,1888024,857458,1030566,509739,250373,259366
7,0,2,30654,15897,14757,23361,12064,11297,7293,3833,3460
8,1,3,31941,16259,15682,24407,12459,11948,7534,3800,3734
9,2,4,35247,18340,16907,27227,14131,13096,8020,4209,3811

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/jJ8mTbGn/Численность населения по полу и возрасту на начало 2020 года_626396.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2020

,Численность населения по полу и возрасту на 1 января 2020 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2391193,1106100,1285093,1866880,848813,1018067,524313,257287,267026
7,0,2,28086,14448,13638,20525,10512,10013,7561,3936,3625
8,1,3,30578,15851,14727,23180,11957,11223,7398,3894,3504
9,2,4,31873,16212,15661,24192,12345,11847,7681,3867,3814

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/Численность населения по полу и возрасту на начало 2021 года_626398.xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2021

,Численность населения по полу и возрасту на 1 января 2021 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Муниципальные образования Иркутской области,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины
5,А,Б,1,2,3,4,5,6,7,8,9
6,Все население,1,2375021,1098190,1276831,1851196,841149,1010047,523825,257041,266784
7,0,2,26811,13771,13040,20390,10446,9944,6421,3325,3096
8,1,3,27980,14391,13589,20445,10472,9973,7535,3919,3616
9,2,4,30449,15770,14679,23080,11882,11198,7369,3888,3481

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/Численность населения по полу и возрасту на 1 января 2022 года (с учетом итогов ВПН-2020).xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2022

,Численность населения по полу и возрасту на 1 января 2022 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Иркутская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Возраст (лет),№№ строки,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN,NaN,NaN
4,NaN,NaN,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,мужчины и женщины,мужчины,женщины,NaN,NaN
5,А,Б,1,2,3,4,5,6,7,8,9,NaN,NaN
6,Все население,1,2363447,1086115,1277332,1834514,827372,1007142,528933,258743,270190,NaN,2787941.0
7,0,2,25265,13011,12254,18799,9724,9075,6466,3287,3179,NaN,NaN
8,1,3,25900,13262,12638,19555,9983,9572,6345,3279,3066,NaN,NaN
9,2,4,27230,13987,13243,19750,10094,9656,7480,3893,3587,NaN,NaN

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/Численность населения по полу и возрасту на начало 2023 года(1).xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2023

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,ЧИСЛЕННОСТЬ НАСЕЛЕНИЯ ПО ПОЛУ И ВОЗРАСТУ \n ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Иркутская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,(человек),NaN,NaN,NaN,NaN,NaN,NaN
4,Возраст (лет),Год,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
5,NaN,рожде-,мужчины,мужчины,женщины,мужчины,мужчины,женщины,мужчины,мужчины,женщины
6,NaN,ния,и женщины,NaN,NaN,и женщины,NaN,NaN,и женщины,NaN,NaN
7,Итого,-,2344360,1075988,1268372,1817199,818221,998978,527161,257767,269394
8,0,2022,24479,12634,11845,18484,9556,8928,5995,3078,2917
9,1,2021,25947,13360,12587,19531,10109,9422,6416,3251,3165

Файл успешно загружен в датасет!

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Найден файл: https://38.rosstat.gov.ru/storage/mediabank/Численность населения по полу и возрасту на начало 2024 года..xls

C:\Users\Lenovo\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '38.rosstat.gov.ru'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

2024

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Численность населения по полу и возрасту на 1 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Иркутская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Возраст (лет),Год,Все население,NaN,NaN,Городское население,NaN,NaN,Сельское население,NaN,NaN
5,NaN,рожде-,мужчины,мужчины,женщины,мужчины,мужчины,женщины,мужчины,мужчины,женщины
6,NaN,ния,и женщины,NaN,NaN,и женщины,NaN,NaN,и женщины,NaN,NaN
7,0,2023,23160,11870,11290,16915,8706,8209,6245,3164,3081
8,1,2022,24376,12583,11793,18428,9543,8885,5948,3040,2908
9,2,2021,25897,13331,12566,19519,10099,9420,6378,3232,3146

Файл успешно загружен в датасет!

In [8]:
for year in years:
    if (year == 2023):
        df_population[year].drop(df_population[year].index[1:2], inplace=True)
    if (year == 2024):
        df_population[year].drop(df_population[year].index[-1:], inplace=True)
    for row_number in range(126, 11, -6):
        df_population[year].drop(df_population[year].index[row_number:row_number + 1], inplace=True)
    df_population[year] = df_population[year].iloc[7:]
    df_population[year] = df_population[year].iloc[:,:5]
    
    df_population[year] =  df_population[year].reset_index(drop=True)
    df_population[year].iloc[100,0] = 100
    
    #path = 'E:/IrkutskProject/Data/'
    #df_population[year].to_csv(f'{path}{year}/avg_population_{year}.csv')

In [9]:
df_population[2016]

,Численность населения по полу и возрасту на 1 января 2016 года,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,0,2,36674,18799,17875
1,1,3,36392,18700,17692
2,2,4,37306,19185,18121
3,3,5,37791,19345,18446
4,4,6,36345,18479,17866
...,...,...,...,...,...
96,96,117,133,21,112
97,97,118,128,19,109
98,98,119,60,21,39
99,99,120,49,8,41
100,100,122,74,24,50

In [10]:
df_population[2023]

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0            0       2022      24479      12634      11845
1            1       2021      25947      13360      12587
2            2       2020      26639      13684      12955
3            3       2019      27824      14315      13509
4            4       2018      30290      15693      14597
..         ...        ...        ...        ...        ...
96          96       1926        295         58        237
97          97       1925        229         47        182
98          98       1924        180         32        148
99          99       1923        131         30        101
100        100       1922        133         39         94

[101 rows x 5 columns]

In [11]:
df_population[2024]

    Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0            0       2023      23160      11870      11290
1            1       2022      24376      12583      11793
2            2       2021      25897      13331      12566
3            3       2020      26552      13630      12922
4            4       2019      27786      14311      13475
..         ...        ...        ...        ...        ...
96          96       1927        314         53        261
97          97       1926        207         49        158
98          98       1925        176         41        135
99          99       1924        150         30        120
100        100       1923        223         61        162

[101 rows x 5 columns]

In [12]:
# year = 2016
df = {}

columns = [
    'Год',
    'Пол',
    'Всего',
    '0-4',
    '5-6',
    '7-14',
    '15-17',
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65+',
    '0-14',
    '15+',
    '0-17',
    '18+'
]

data = []

for year in years:
    for col_number in range(2, df_population[year].shape[1]):
    
        new_row = []    
        new_row.append(year) # Год
        if (col_number == 2): # Пол
            new_row.append('всего')
        if (col_number == 3):
            new_row.append('мужчины')
        if (col_number == 4):
            new_row.append('женщины')

        #Всего
        value = 0
        for row_number in range(0, df_population[year].shape[0]):
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)
    
        # 0-4
        value = 0
        for row_number in range(0, 5):
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 5-6
        value = 0
        for row_number in range(5, 7): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 7-14
        value = 0
        for row_number in range(7, 15): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)
      
        # 15-17
        value = 0
        for row_number in range(15, 18): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 18-24
        value = 0
        for row_number in range(18, 25): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 25-34
        value = 0
        for row_number in range(25, 35): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 35-44
        value = 0
        #for row_number in range(35, 44): 
        for row_number in range(35, 45): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 45-54
        value = 0
        #for row_number in range(45, 54): 
        for row_number in range(45, 55): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 55-64
        value = 0
        #for row_number in range(55, 64): 
        for row_number in range(55, 65):
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 65+
        value = 0
        for row_number in range(65, df_population[year].shape[0]): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 0-14
        value = 0
        for row_number in range(0, 15): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 15+
        value = 0
        for row_number in range(15, df_population[year].shape[0]): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 0-17
        value = 0
        for row_number in range(0, 18): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        # 18+
        value = 0
        for row_number in range(18, df_population[year].shape[0]): 
            value += df_population[year].iloc[row_number, col_number]
        new_row.append(value)

        data.append(new_row)
    
df = pd.DataFrame(data, columns=columns)

In [13]:
# Промежуточный результат. Абсолютные значения
df

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17,18+
0,2016,всего,2412800,184508,68365,231220,74809,196504,411756,346933,294948,318766,284991,484093,1928707,558902,1853898
1,2016,мужчины,1115508,94508,34959,118511,38540,98210,207138,165788,136331,132933,88590,247978,867530,286518,828990
2,2016,женщины,1297292,90000,33406,112709,36269,98294,204618,181145,158617,185833,196401,236115,1061177,272384,1024908
3,2017,всего,2408901,183080,70049,239152,75149,183862,406890,349587,287933,318660,294539,492281,1916620,567430,1841471
4,2017,мужчины,1113729,94230,35690,122656,38747,91663,205544,166899,133131,133218,91951,252576,861153,291323,822406
5,2017,женщины,1295172,88850,34359,116496,36402,92199,201346,182688,154802,185442,202588,239705,1055467,276107,1019065
6,2018,всего,2404195,177110,73839,245329,78081,175602,395025,353974,284907,316167,304161,496278,1907917,574359,1829836
7,2018,мужчины,1111049,91120,37669,125689,40076,88009,199472,169328,131782,132510,95394,254478,856571,294554,816495
8,2018,женщины,1293146,85990,36170,119640,38005,87593,195553,184646,153125,183657,208767,241800,1051346,279805,1013341
9,2019,всего,2397763,170405,74605,253078,80547,172072,379206,358786,283865,312297,312902,498088,1899675,578635,1819128
10,2019,мужчины,1107831,87775,38286,129524,41171,86432,191541,172365,131098,131139,98500,255585,852246,296756,811075
11,2019,женщины,1289932,82630,36319,123554,39376,85640,187665,186421,152767,181158,214402,242503,1047429,281879,1008053
12,2020,всего,2391193,161919,73060,261800,82717,170613,365834,361786,286289,304210,322965,496779,1894414,579496,1811697
13,2020,мужчины,1106100,83410,37613,133901,42400,86219,185316,174743,132347,128251,101900,254924,851176,297324,808776
14,2020,женщины,1285093,78509,35447,127899,40317,84394,180518,187043,153942,175959,221065,241855,1043238,282172,1002921
15,2021,всего,2375021,152059,72108,270803,82635,170381,349921,364341,288842,295255,328676,494970,1880051,577605,1797416
16,2021,мужчины,1098190,78358,37053,138537,42260,86296,177615,176470,133140,124847,103614,253948,844242,296208,801982
17,2021,женщины,1276831,73701,35055,132266,40375,84085,172306,187871,155702,170408,225062,241022,1035809,281397,995434
18,2022,всего,2363447,138740,69334,270987,80147,168046,312164,383464,300844,293884,345837,479061,1884386,559208,1804239
19,2022,мужчины,1086115,71294,35768,138682,41433,86115,155776,183936,138113,124830,110168,245744,840371,287177,798938
20,2022,женщины,1277332,67446,33566,132305,38714,81931,156388,199528,162731,169054,235669,233317,1044015,272031,1005301
21,2023,всего,2344360,135179,66444,280760,84879,172534,288036,386215,303222,280572,346519,482383,1861977,567262,1777098
22,2023,мужчины,1075988,69686,34263,143810,43888,88021,143460,185246,138161,119224,110229,247759,828229,291647,784341
23,2023,женщины,1268372,65493,32181,136950,40991,84513,144576,200969,165061,161348,236290,234624,1033748,275615,992757
24,2024,всего,2330537,127771,61716,281377,91717,174343,269012,388659,307305,271701,356936,470864,1859673,562581,1767956
25,2024,мужчины,1068992,65725,31704,144504,47206,89016,134817,186602,139659,115967,113792,241933,827059,289139,779853
26,2024,женщины,1261545,62046,30012,136873,44511,85327,134195,202057,167646,155734,243144,228931,1032614,273442,988103

In [14]:
def round_math(num):
    if num >= 0:
        return math.floor(num + 0.5)
    else:
        return math.ceil(num - 0.5)

In [15]:
df_avg = {}
columns = [
    'Год',
    'Пол',
    'Всего',
    '0-4',
    '5-6',
    '7-14',
    '15-17',
    '18-24',
    '25-34',
    '35-44',
    '45-54',
    '55-64',
    '65+',
    '0-14',
    '15+',
    '0-17',
    '18+'
]
data = []

for row_number in range(0, df.shape[0] - 3):
    new_row = []
    new_row.append(df.iloc[row_number, 0])
    new_row.append(df.iloc[row_number, 1])
    
    for col_number in range(2,df.shape[1]):
        value = round_math((df.iloc[row_number, col_number] + df.iloc[row_number + 3, col_number])/2)
        new_row.append(value)
    data.append(new_row)
df_avg = pd.DataFrame(data, columns=columns)
result = pd.concat([df_avg, df.iloc[-3:]], ignore_index=True)
display(result)

,Год,Пол,Всего,0-4,5-6,7-14,15-17,18-24,25-34,35-44,45-54,55-64,65+,0-14,15+,0-17,18+
0,2016,всего,2410851,183794,69207,235186,74979,190183,409323,348260,291441,318713,289765,488187,1922664,563166,1847685
1,2016,мужчины,1114619,94369,35325,120584,38644,94937,206341,166344,134731,133076,90271,250277,864342,288921,825698
2,2016,женщины,1296232,89425,33883,114603,36336,95247,202982,181917,156710,185638,199495,237910,1058322,274246,1021987
3,2017,всего,2406548,180095,71944,242241,76615,179732,400958,351781,286420,317414,299350,494280,1912269,570895,1835654
4,2017,мужчины,1112389,92675,36680,124173,39412,89836,202508,168114,132457,132864,93673,253527,858862,292939,819451
5,2017,женщины,1294159,87420,35265,118068,37204,89896,198450,183667,153964,184550,205678,240753,1053407,277956,1016203
6,2018,всего,2400979,173758,74222,249204,79314,173837,387116,356380,284386,314232,308532,497183,1903796,576497,1824482
7,2018,мужчины,1109440,89448,37978,127607,40624,87221,195507,170847,131440,131825,96947,255032,854409,295655,813785
8,2018,женщины,1291539,84310,36245,121597,38691,86617,191609,185534,152946,182408,211585,242152,1049388,280842,1010697
9,2019,всего,2394478,166162,73833,257439,81632,171343,372520,360286,285077,308254,317934,497434,1897045,579066,1815413
10,2019,мужчины,1106966,85593,37950,131713,41786,86326,188429,173554,131723,129695,100200,255255,851711,297040,809926
11,2019,женщины,1287513,80570,35883,125727,39847,85017,184092,186732,153355,178559,217734,242179,1045334,282026,1005487
12,2020,всего,2383107,156989,72584,266302,82676,170497,357878,363064,287566,299733,325821,495875,1887233,578551,1804557
13,2020,мужчины,1102145,80884,37333,136219,42330,86258,181466,175607,132744,126549,102757,254436,847709,296766,805379
14,2020,женщины,1280962,76105,35251,130083,40346,84240,176412,187457,154822,173184,223064,241439,1039524,281785,999178
15,2021,всего,2369234,145400,70721,270895,81391,169214,331043,373903,294843,294570,337257,487016,1882219,568407,1800828
16,2021,мужчины,1092153,74826,36411,138610,41847,86206,166696,180203,135627,124839,106891,249846,842307,291693,800460
17,2021,женщины,1277082,70574,34311,132286,39545,83008,164347,193700,159217,169731,230366,237170,1039912,276714,1000368
18,2022,всего,2353904,136960,67889,275874,82513,170290,300100,384840,302033,287228,346178,480722,1873182,563235,1790669
19,2022,мужчины,1081052,70490,35016,141246,42661,87068,149618,184591,138137,122027,110199,246752,834300,289412,791640
20,2022,женщины,1272852,66470,32874,134628,39853,83222,150482,200249,163896,165201,235980,233971,1038882,273823,999029
21,2023,всего,2337449,131475,64080,281069,88298,173439,278524,387437,305264,276137,351728,476624,1860825,564922,1772527
22,2023,мужчины,1072490,67706,32984,144157,45547,88519,139139,185924,138910,117596,112011,244846,827644,290393,782097
23,2023,женщины,1264959,63770,31097,136912,42751,84920,139386,201513,166354,158541,239717,231778,1033181,274529,990430
24,2024,всего,2330537,127771,61716,281377,91717,174343,269012,388659,307305,271701,356936,470864,1859673,562581,1767956
25,2024,мужчины,1068992,65725,31704,144504,47206,89016,134817,186602,139659,115967,113792,241933,827059,289139,779853
26,2024,женщины,1261545,62046,30012,136873,44511,85327,134195,202057,167646,155734,243144,228931,1032614,273442,988103

In [16]:
path = 'E:/IrkutskProject/Data/'
result.to_csv(f'{path}Common/avg_population_2016-2024.csv', index=False)